# Generated by Django 4.2.6 on 2023-11-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_futbol', '0002_articulo_alter_jugador_altura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
    ]
