# Generated by Django 4.2.6 on 2023-11-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_futbol', '0003_delete_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=256)),
                ('contenido', models.CharField(max_length=1000)),
            ],
        ),
    ]
