# Generated by Django 4.2.6 on 2023-11-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_futbol', '0005_articulo_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
