# Generated by Django 4.2.6 on 2023-11-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_futbol', '0008_articulo_creador_club_creador_entrenador_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='entrenador',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='creador',
        ),
    ]
