# Generated by Django 4.2.6 on 2023-11-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_futbol', '0009_remove_club_creador_remove_entrenador_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='autor',
        ),
    ]
